#!/usr/bin/env python3
"""
Regenerates src/lib/resume/fonts.generated.ts

Subsets Inter and Source Serif 4 (both SIL OFL 1.1) to Latin + Latin Extended-A +
common punctuation + the rupee sign, strips layout tables (pdf-lib does not apply
GSUB/GPOS, and dropping them guarantees no ligature/contextual-alternate glyphs that
could confuse ATS text extraction), and inlines the result as base64.

Usage:
  npm i --no-save @expo-google-fonts/inter @expo-google-fonts/source-serif-4
  pip install fonttools
  python3 scripts/build-fonts.py node_modules/@expo-google-fonts
"""
import base64, os, subprocess, sys, tempfile

root = sys.argv[1] if len(sys.argv) > 1 else "node_modules/@expo-google-fonts"
UNICODES = ",".join([
    "U+0020-007E", "U+00A0-00FF", "U+0100-017F", "U+02C6", "U+02DC", "U+2010-2015",
    "U+2018-201A", "U+201C-201E", "U+2020-2022", "U+2026", "U+2030", "U+2039-203A",
    "U+20AC", "U+20B9", "U+2122", "U+2190-2193", "U+2212", "U+2248", "U+2260", "U+2264-2265",
])
FACES = {
    "sansRegular":  "inter/400Regular/Inter_400Regular.ttf",
    "sansSemibold": "inter/600SemiBold/Inter_600SemiBold.ttf",
    "sansItalic":   "inter/400Regular_Italic/Inter_400Regular_Italic.ttf",
    "serifRegular":  "source-serif-4/400Regular/SourceSerif4_400Regular.ttf",
    "serifSemibold": "source-serif-4/600SemiBold/SourceSerif4_600SemiBold.ttf",
    "serifItalic":   "source-serif-4/400Regular_Italic/SourceSerif4_400Regular_Italic.ttf",
}
out_path = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "resume", "fonts.generated.ts")
lines = [
    "// AUTO-GENERATED by scripts/build-fonts.py — do not edit by hand.",
    "// Inter (c) The Inter Project Authors; Source Serif 4 (c) The Source Serif 4 Project Authors.",
    "// Both licensed under the SIL Open Font License 1.1 — see FONT-LICENSES.md.",
    "export const FONT_DATA = {",
]
total = 0
with tempfile.TemporaryDirectory() as tmp:
    for key, rel in FACES.items():
        src = os.path.join(root, rel)
        dst = os.path.join(tmp, key + ".ttf")
        subprocess.run([
            "pyftsubset", src, f"--unicodes={UNICODES}", "--layout-features=", "--no-hinting",
            "--drop-tables+=DSIG,GDEF,GPOS,GSUB", "--name-IDs=*", "--notdef-outline",
            f"--output-file={dst}",
        ], check=True)
        data = open(dst, "rb").read()
        total += len(data)
        lines.append(f'  {key}: "{base64.b64encode(data).decode()}",')
lines.append("} as const;")
lines.append("")
lines.append("export type FontKey = keyof typeof FONT_DATA;")
open(out_path, "w").write("\n".join(lines) + "\n")
print(f"wrote {os.path.normpath(out_path)} ({total/1024:.0f} KB of TTF before base64)")
